apiVersion: v1
kind: Secret
metadata:
    name: slskd
    namespace: media
type: Opaque
stringData:
    SLSKD_USERNAME: ENC[AES256_GCM,data:GQuJKG4=,iv:0RMEIljB6Yuh9gczwbH9C+pXV9RuW6+2zonH7qAQBt4=,tag:sNYK6jyWzljCC8hiTsJd1g==,type:str]
    SLSKD_PASSWORD: ENC[AES256_GCM,data:hFZYqpIjcX0=,iv:vFsi0ecd3pe7RYqRBJ++aDsTFz8eeFqNz94ElKqpTJw=,tag:1lEE/4FUHPFoaQkOgyKlfA==,type:str]
    SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:/BoQsGUjKo+PSQ==,iv:9zPp7/gUp/5wFkXpflAMonIKk4LvCaljKuWZTyuJMt0=,tag:IPspFVi6nBCns7Wj68gokQ==,type:str]
    SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:2A2+5dh/mny96AuvxZqRlGtgofwk19wi,iv:olOMtA6BADfokxtKElP1c4PMloLyz5FJI9jpcJkXNuw=,tag:FHTcN89ngEjXbTpjv1BIMw==,type:str]
    SLSKD_VPN_GLUETUN_API_KEY: ENC[AES256_GCM,data:eR9MKFJvPU7sus43xrs5TVl+uxxP+g==,iv:Wlh1kSNlkBgFyE4j9vo7KsPL/sLdi/JDsh2sbEjzGfs=,tag:C1ojlS2dpSWJIgrZ3Hb11Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeGdMT3JKUWVDNHlQNE5D
            a29iUlRWbWJLT2ZGK2VTRGRoUFZSWXdMM1dnCmZNVlJUWE56T2ZyZ2ttUHJEY0dL
            WHRSdFhDMGlNa0REK1Z6dlRnVytOaWsKLS0tIEc4VG01UU1TcG9GK09LejBpUDZx
            RzB5VE1ZZGdQV0ZyRVZlV3BMZUVvNGMKFsbFzc87Htp5bDt8VQ3Ib5vxetOy+nEi
            9S9sLcqsJUKl9mMxNDz8Dz9KOPRP6HMVdC4O8vUG1jsjK4bw6EslYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ckmnwzymn6wkqxhyre5kve3leqj5697c59wv3p67jyc5ukzzxpxqxws9wp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T21:39:15Z"
    mac: ENC[AES256_GCM,data:bReFXO/3sX0isvnf3PxyBXttbrIUuISu/DtCct3/MGOeBm5SucHuLLTXCzfsypi1Vi8j7Vnc3q5FPNUrcZDzXEl7IcF5reO+39yCV386YBvDmuuh1pc0k6eq/1o9CH2g7TlueY4nDWk7wFPOVj65cGxFpHYyCN0w3Zl4L4hEHJc=,iv:4cvPQqI56FiDTip4ie3FG3wgfBFVlAfnMk6dYRpVOPY=,tag:MkLHCpxPisBrNyC/hd7eqA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: slskd-yaml
    namespace: media
type: Opaque
stringData:
    slskd.yml: ENC[AES256_GCM,data:hqFLGJTmKCjSwUV5/yLvTaA9d9Qwrl6ZXnKkoMbdnR2qKJwF7oB8/bhxFmTupRwrjUqSuAVXmyx6ukTAkDEx2FsBGpMXvtnnlVCd1sGD8pbJDZreiLS3rg==,iv:LdjlZY2Q/j/NB6ISrMXOFw7lR0IG1KMRfNczwbvSHlE=,tag:aIC75rf6PnARaJKR/6quXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeGdMT3JKUWVDNHlQNE5D
            a29iUlRWbWJLT2ZGK2VTRGRoUFZSWXdMM1dnCmZNVlJUWE56T2ZyZ2ttUHJEY0dL
            WHRSdFhDMGlNa0REK1Z6dlRnVytOaWsKLS0tIEc4VG01UU1TcG9GK09LejBpUDZx
            RzB5VE1ZZGdQV0ZyRVZlV3BMZUVvNGMKFsbFzc87Htp5bDt8VQ3Ib5vxetOy+nEi
            9S9sLcqsJUKl9mMxNDz8Dz9KOPRP6HMVdC4O8vUG1jsjK4bw6EslYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ckmnwzymn6wkqxhyre5kve3leqj5697c59wv3p67jyc5ukzzxpxqxws9wp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T21:39:15Z"
    mac: ENC[AES256_GCM,data:bReFXO/3sX0isvnf3PxyBXttbrIUuISu/DtCct3/MGOeBm5SucHuLLTXCzfsypi1Vi8j7Vnc3q5FPNUrcZDzXEl7IcF5reO+39yCV386YBvDmuuh1pc0k6eq/1o9CH2g7TlueY4nDWk7wFPOVj65cGxFpHYyCN0w3Zl4L4hEHJc=,iv:4cvPQqI56FiDTip4ie3FG3wgfBFVlAfnMk6dYRpVOPY=,tag:MkLHCpxPisBrNyC/hd7eqA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: slskd-gluetun-config
    namespace: media
type: Opaque
stringData:
    config.toml: ENC[AES256_GCM,data:5uPK9XAkr1xREwTz++rcLLfmbpcAFZpT7x4443d1Us77xd32ZvuLq6eO2Xkdz1Aqmpp9JoU34cQtydEMo0qTKyWNN3rxaEyNvPHCF1fSqFzo3EW6rjSDIRCCHocgVmA2VJ7Y0ILDBabSKHSxIkhm+fgRs6JxBLWWXWuxPao3xNgzEy97fkrOPzeRffs4rWQm36xoKk4Qim98ETJAcV8EbNZGXY4MJs3KJbo8p0EBF0hLHul1riNd1dZpGCd6sEng5qEnwkHKqQZ006mNDUWPovWgUFimGTDFSDcjX4ZPzklhK6t9AeYv+VICaZecIPblZp8dISgVI7iWgqByGktfDOKmzSK/SnFvR7KJYMAhULLUxuiifqkMl4gVRRJsG3Daftk1xQTVk1oPwbk=,iv:k2Wy4BMnIN2eC5IhMx4j3bP6SdNIMyNonvAz2yQlFIU=,tag:VU7F8IpePk2f6Rm1ki31OQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeGdMT3JKUWVDNHlQNE5D
            a29iUlRWbWJLT2ZGK2VTRGRoUFZSWXdMM1dnCmZNVlJUWE56T2ZyZ2ttUHJEY0dL
            WHRSdFhDMGlNa0REK1Z6dlRnVytOaWsKLS0tIEc4VG01UU1TcG9GK09LejBpUDZx
            RzB5VE1ZZGdQV0ZyRVZlV3BMZUVvNGMKFsbFzc87Htp5bDt8VQ3Ib5vxetOy+nEi
            9S9sLcqsJUKl9mMxNDz8Dz9KOPRP6HMVdC4O8vUG1jsjK4bw6EslYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ckmnwzymn6wkqxhyre5kve3leqj5697c59wv3p67jyc5ukzzxpxqxws9wp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T21:39:15Z"
    mac: ENC[AES256_GCM,data:bReFXO/3sX0isvnf3PxyBXttbrIUuISu/DtCct3/MGOeBm5SucHuLLTXCzfsypi1Vi8j7Vnc3q5FPNUrcZDzXEl7IcF5reO+39yCV386YBvDmuuh1pc0k6eq/1o9CH2g7TlueY4nDWk7wFPOVj65cGxFpHYyCN0w3Zl4L4hEHJc=,iv:4cvPQqI56FiDTip4ie3FG3wgfBFVlAfnMk6dYRpVOPY=,tag:MkLHCpxPisBrNyC/hd7eqA==,type:str]
    version: 3.13.3
