apiVersion: v1
kind: Secret
metadata:
    name: nemorosa
    namespace: media
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:d2nu0WPpxN0G4OP4jozzfSBrvt5g1XO7Ux7Ar21ak8dFxutw0HPRfwEPrTOjgZN9jRWV8QWnksQAGEL1ULmhIUCJImujjMj97t8gmPcSIZjv/EmQ/NKgOqIY1sqHytf/EO+HdR9aE058EdlVIZ1ze7rAPaZK9Yx3cq7NrtBMgENg+BxOm3FWEqH2FuswD9qDIB8Idj1TqC4u566kn8BfbmF2XeonjsitVv5KPhcTErhBeXMbdoOipZsdXoxvHjObOpFQyLmWrmzFz/arGnHX0gnNVA4GTPvKjQNqFW3caklkpc/Fr2P/P/5UcLcNvic4rq+v2NcogbQ8uvIqX1/ZYfAbRkFGMZP+hGW6koRyF+EZdHLCb9QWZg2CcZ+lXFPV5tQQWcTm4DxIJiWDCczd7et59Cwgco1YmPzh8TGAcimaXx6pfKyNcuJJ6rq6x+pmp75lLSTFARjms06Lvn+CUhribBoy4Fcd7qYxzCzMOQqSdfaj8Oib8E8M5TjMfHrF++ucn3WKaq6b4Wi8q+qsGvn2W6PtWR4gBsGnmLWznnmH7GwBjVEtNtkHn+au/eHTJk7K+4UtKLrx3OlwVTrtucKeRXS9jfu/UFWk2aNLRSaylhgSzlajBRHdBS5wPkDBMCdmkXVCnSI4yOvG6mTfFir3adSN10mYZVDveCtVqyDVMx9Ro00ysGjUX5KgK/Om9pSK/dpibMB+TbioP37VmDb8KPinZjEw1fj051s8G5Q+3BnVwEqOF+10E9Nqe3/E0Xep1rndM53682z+A1tXzEOXkeY/VUiUZaWPuNeO9NHiUqsSDCqcv/bae8zOOv/8CacfBuCzhfgTW//zHxyCov/mxRPU20DIl0lGwp6EoAE+v5V34Kuei53c7I8L9wzsDhgBY5KLyqX8LTotcD9gfmhJQfitxFDm/s1jzNY3LLDfHD+jIm3v7RlPejNLKbTRq6sMM3au2tCQ8yNbousPQyFPLryDjUVFpYZVHKPnG8SAErwaWUlTAuG7ft62qkOKsQsWRHvtqfXzlYh6S5X2rCXbTDaN7AxnCuhOMxpRc4LnTJ79pjhygi5gsL5rr0F23G8eiOrarPpvYEO1QZSFhv2b/DI0Ycwhnp97/d5W+pYVMcPa4kaCJNk1KZeIm7o/7bcBSKjcOFgW6Pj1nKHzHoPPYzfTRD8G3zmdi5+t05w0NEl0+lyR7Pd6utnoPmz7JzJjJE9cM4cZTCiXN4Qw2b54evPkVk8+HQFBeDTnhLA2zkhmz7lce1p3m47QWG7cGk2yhPb+lS93AoTo1fEJK7mUzypUk8qMte6lw9kFVbJA+RvI3BHu7GfkA0+HZWKjFSIUqWdBbIHmqrrlUjAds0g1XYjFgWfsDEhgarWlAmziu1ZQ1ktqz27X8sGJv+s6zeg1gs2FBfGpf/Gp/XWfYssajVWqyT/dLTR1FVnmjZk1sidJ4B+jupi+Ss0O5QGPURaHQa5BXVOOgSiUeKP5M5DMVKvg/p3m9jx+80n1fzBqx+j0RnDvQXDSrAo46FUYfB1erJz57SzmpnVimrB3jUefu/R2rZTmiN8ybz+P2AoJHzqowtnMj6DIqgk4jQBNEgv2NizHz8E71pEEDoOvDIhypnuZ1z21kQ==,iv:7Bk8SnR7z6b7ofRfvKWsUcmth0PZKSdzXNnMiQ3P5N8=,tag:Y07MrTG/H2nTN4OY9dLjSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcmo2RTA3RzdCRVhXb3pu
            QVp2S2k4TTJxaEU2Ukowa2VNTTlNMC8rS1JNCjBTNXZSSDVrdVVYa3plMWNWZ0Vt
            cnhjU1FiMEVmNUlqWFdIQ0E2cDNvQ2MKLS0tIGNXWkh4emNUakhXYXZrWkNsNGQw
            QVVacEFTcVhaMktyZG83R3F6Nlhmc28KQxcR8be2ul2zWfQXaAack1muVwkrqg/+
            V/uy79gmdpU890kfXj4BGEqLm1NrTftuJcZDzk8qoF8TMHjYny5Aog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ckmnwzymn6wkqxhyre5kve3leqj5697c59wv3p67jyc5ukzzxpxqxws9wp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-11T15:25:09Z"
    mac: ENC[AES256_GCM,data:s+Nns09t7HLJWA2kfanBWkumDt+cIIKgejgsKFO19uH0QqKqNWoN8CupasmVqGoRZOv/HLTkfXi8PKNyLAFf12TaO2cfpfLXbwY0S9uqU09GxqL6JA72Qoax38e3ucUGYZeWUXyjVGKebeLB5GMOZUxtqRMqQHMZ0SBUOs48Awc=,iv:WbURgzslARNjHbWuxg6o9RCI3qR2yPiEt1ZxWB+3l0g=,tag:Hz6pmSTix4hgCpVDcMRwFw==,type:str]
    version: 3.13.3
