apiVersion: v1
kind: Secret
metadata:
    name: nemorosa
    namespace: media
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:Mx5PzaUurPE9JCQwvkYLypvPTJP5JDTRX6+z2I3avwhHYj+l5Cz5v9c2v52GK29WDeZo9rZtFj0oIoj2p8CIEOAGqNXBuKUtyAPI64G3uVzg4eqiD1F9l5nU83fFnSo8UuaWlZhxKxzXvvHSvzP2E7u0GciOBNdT56o0vNTjgAQpCjFZkeStcK7u5J9Kfj9SU9CEP2rfDWcGwoiKKHPKI2w5/YTfWw2t7tSF5JNulq73+Y0HDmFCepwBtBiUJ5KkjRyqtVcmZsgEutbBn6mhlRKDqNdXQ3mB+049y3Af43AS4GjlpYjqSbqAu6OTGz0jkyOetSHPqjl8tMadrDk5jHl6J71PJFU6RkoPY9j/CVx4xXdJ3XgaZMRRBJHjZtKgvJlQ23XsycNf9S7GhGjrYsojlGr0rpG4DLopOiLwipROn2URWw5gveiMFVvauTY5U079ZcP+p1co9z7DMkLFDZImVFZ9mMRkXoqtIwW4a/gnUdJy2kM97Zbno7fRy0+PPH77MQ6joiv1gdQ1je91x9owa0OrGPmuP6ALvt80g5vADyKKpO+YzcfU22D6B6nQXTdR9ywrHBjAegDxjW6snuS/CxWYbayoVm+duBVnlUeF4GkdXHXkF47wOlnUA0Lp+2pCjhl/euA0PemHesgZ2vr1b17ihz4bXz1yUm69ytWdTqp8MyFo99A4p5F+M6CLGld/KlOClyzgZIrFOY7SaLh07nQ3SUFwZ2mA9mvxVp1UiASmF6QdAF/5MBnK64xxjbO1KKBXYJRGJYxKtagj9AjS9ShDZTuTb5L5crs5jp4OtRrf0TM4TuI+RAjgXiSnDcoTNQgD6EpEkVH/ExHoy0tkoTt9Nrv6dcGWVwp+ZjtgiChvsMeeti0ZhOnydc0VlNYJLDDNQz6ZGHJz4QEkDPkWXygwZVsgdQNKcIQLh/0LKSKhVd/qwlmRTDAw1fdxLW7dBmcVXkMmRrLe8P2+VJMbqy35RSBK13y3TbJwgRpTzlC1PUrAA83LCT23S+WgcxqUcI3/W+yKrUFlBBE1h9WsEQ7b4oiEoLh+UDzaM045/ZfGY88mBS2IW0enSjwqnlCWrBebIMVDGDgU+WHWYdoFd9FS5GvKwKiwD8FnNl8ur3ADrVAaZ2xp9UqZGiT/6ICjKW2TQzfEE8Th3C/ER6R9yoi+cyj1tv2n/UmwJ+dongsOEYoPuw4vTqhTyRri1GFnWGzZA/irAH/OO7qjE9/73uSllWlcF895vL5l7k71/1NshEEh9UrdC1qMQsdmSkUgWa5+Lo5Lc2blhZIV8po80wJlTldy+jT5AdWF1sB8r1+cuA6NfeAkiz2fl5RCtufmFBjXuqweumdMveEwEn6l2z01xs2GCyhTMR5BNi/hjx0h1jaw6lhRqaGDcm7ZRZnz9IMeoy6OaPJbbPh+S86qAEWYF/Iqin3wp6MHYgSU6JNmto+BaTFyrBw8nQczb0gA9OqilNRJtcQQqBxzmIrYJ8EEurKoyUvJOm+xRKw4MnkLL/FlgtJiKjfFIg4LdQkJhPdkRm3C/+1khhHAUx43cmZwzc6mE6iy8fpbROQDcm3vW6s52EN96+RYyCZnxX9wl82vZSo5qJRSF6MjKz0=,iv:6zuLVhNXjSiDt91QjoRp1Y+viv7FInmGcl19ja2d49U=,tag:fH01opVgYxrNo5QBISLU2w==,type:str]
sops:
    age:
        - recipient: age1ckmnwzymn6wkqxhyre5kve3leqj5697c59wv3p67jyc5ukzzxpxqxws9wp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcmo2RTA3RzdCRVhXb3pu
            QVp2S2k4TTJxaEU2Ukowa2VNTTlNMC8rS1JNCjBTNXZSSDVrdVVYa3plMWNWZ0Vt
            cnhjU1FiMEVmNUlqWFdIQ0E2cDNvQ2MKLS0tIGNXWkh4emNUakhXYXZrWkNsNGQw
            QVVacEFTcVhaMktyZG83R3F6Nlhmc28KQxcR8be2ul2zWfQXaAack1muVwkrqg/+
            V/uy79gmdpU890kfXj4BGEqLm1NrTftuJcZDzk8qoF8TMHjYny5Aog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T07:43:40Z"
    mac: ENC[AES256_GCM,data:rKK+LOIbnxTJz1AIWHCL5oW1fEC93r0I6MjqyqyEJHF5RrYABQ4AWO53RzHttCpmnK6aQmxkkAPOXCxej9O31Ej5Jri5WNTqT412//mCiFHRnQtb0UYLzNWZuxV6x1fMR0+VR3A1b4qUw6TP6zuf76tScqRdw1kVuP3kBa6Xilo=,iv:ltWr9vG8P085RYFOY9cbv8GzELu0I3CmYzMj4IeNYGw=,tag:DOWLmEYcBmIjm5Yx8C6nPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
