apiVersion: v1
kind: Secret
metadata:
    name: webhook
    namespace: monitoring
type: Opaque
stringData:
    GLUETUN_API_KEY: ENC[AES256_GCM,data:PvzI1hBxrv6I99FJkh06gN9KidPq5w==,iv:SBJgR3NHIkBqWRMbjibnprUE5+pZeIFdQY7pKnvVwgM=,tag:oxnIPUOntd0cbyCm9JNkbw==,type:str]
sops:
    age:
        - recipient: age1ckmnwzymn6wkqxhyre5kve3leqj5697c59wv3p67jyc5ukzzxpxqxws9wp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeGdMT3JKUWVDNHlQNE5D
            a29iUlRWbWJLT2ZGK2VTRGRoUFZSWXdMM1dnCmZNVlJUWE56T2ZyZ2ttUHJEY0dL
            WHRSdFhDMGlNa0REK1Z6dlRnVytOaWsKLS0tIEc4VG01UU1TcG9GK09LejBpUDZx
            RzB5VE1ZZGdQV0ZyRVZlV3BMZUVvNGMKFsbFzc87Htp5bDt8VQ3Ib5vxetOy+nEi
            9S9sLcqsJUKl9mMxNDz8Dz9KOPRP6HMVdC4O8vUG1jsjK4bw6EslYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T19:47:02Z"
    mac: ENC[AES256_GCM,data:kRVbItEN8Xxb9brKXuyu0bJZbvii3tMBcKl59ZxCl3kjTZeFShxpWhwzt6pMDatXIHjxmknuMhmIA0aPNnNoOG1SIyA8kTFCfMlqPLXGbDtgpNCCSEQG+3jhSX6UoXKJIW38S77nxfZ3QHXLPleIVJBf1ubXsz2yjRM98YhZsvw=,iv:T/twxxZqgutPmqqIsGoKHCLOltwLUiYalJ4T01GJHnQ=,tag:RKJcLXsftJuHhxj3ut4jXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
