apiVersion: v1
kind: Secret
metadata:
    name: backrest
    namespace: storage
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:e8lMWn5SSAM=,iv:Uxj5Ctvs1EhbvPsIfxV3MjkjmrUNex7vDKPsu+ckvug=,tag:zZC/d5eyh+qlWkiHL92BWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYVpaYzM0TVFjanVtaS9H
            VU9WcGhIL0NjMWFDVC81aGdPMkNJc0prY2xFCnZTd0tIUUwrNGpwMHpSaUR0dzBM
            UWZrWTNwTCtGazFvTHJ3U0JhN3hXWUEKLS0tIFA3djQydnVFb0s4RnpBQ3BIR01v
            OFZEd0w0VThyTmNMYnlpdmJERGJuU1EKxQ/pYmevCp5otlwJ6Zb/dwBKp9567HRQ
            evpV9TX6Rd70AC7Gcijm5Eb1Pf/Lgp74dwJ1JUmxvASw/uGvx1NsNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ckmnwzymn6wkqxhyre5kve3leqj5697c59wv3p67jyc5ukzzxpxqxws9wp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T02:54:39Z"
    mac: ENC[AES256_GCM,data:9wyG2D5SKHW2qJ73kUmU7dlKKF8BobrCtt/z+Yhq/8F7lRdXLgYyVn2GppSWw0Vx01I/tMfIg4+9aDOt3tGcQiMPsFhJOlKilDGlbk3AZd+AGL8Z/IihWW3rhXuX6mt+q5rzUGFwh9UzXOSX7bH8AfTCS5GfIyeW9veMxOln0fM=,iv:NyXN/tL9rXub90wI++LQa7YHy2nls8/lFmjo4RjHINM=,tag:PrPV5S7gn2aWvFXuEU6K2w==,type:str]
    version: 3.13.3
