apiVersion: v1
kind: Secret
metadata:
    name: gluetun-proxy
    namespace: networking
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:JVWB7On/tqVeo6lyqsP1Ri1pzZwULWdQaAFXG85X4a04LuGqVpOWwuKTEj8=,iv:RjhkhhrIVOZjcsPyARAb9KGPZBoyoeDsP0Ftlqn0I8g=,tag:LYJmP5JS6TDfveNPcmUaaA==,type:str]
sops:
    age:
        - recipient: age1ckmnwzymn6wkqxhyre5kve3leqj5697c59wv3p67jyc5ukzzxpxqxws9wp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aktoZEs0NEt3SFpkNUxs
            RzZKS3d1YjB1cXNnUTM5cFhCZ3Uwajd6aUI4CmROcjFPZEtUb0kvMzFmK0ZYWHN0
            Q3FpQVVDRHUyUnlKWFN3T05BRi9hdWcKLS0tIDhzL3ozeWM5VGNLOWY2MUg4SDEv
            TG5GMXUrUXEza3Q5LytLYm1ZdnVhS3cKANvyWRgEpPn432ufcsj0Nk8aXJBvyKev
            0t2EvkP2DT2uQ/QTuFjgVBACy1f6WzAQ/siCkH9/C5Wv7pME3t5s9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T15:55:32Z"
    mac: ENC[AES256_GCM,data:R4mL3yZOfBn9g9Kj8qj9tR4m6dQczG/6acve4pmUrFoKjfm9/sL9W59mUvqYxStFN1NvKilvj7OanTd/pA1yZP2BH5rVMfFIRmUgGtJobOaUTNUqymVLOtrc8pDW4mHOQWActLO7Msx6kcRG2w2BYUWsxJKoZYjjkLBmdZCOuWU=,iv:rvhy/CauBnuCzlYkTMfMDcXBg/kp4rXeYqzi052oEGQ=,tag:50EL4rh/zr5vznbfKiCvAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
