---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./restore.yaml
  - ./backup.yaml
  - ./gatus.yaml
configMapGenerator:
  - name: navidrome
    files:
      - navidrome.toml=./resources/navidrome.toml
      - run_scripts.sh=./resources/run_scripts.sh
      - navidrome_cache_sorted.py=./resources/navidrome_cache_sorted.py
      - navidrome_queue_to_playlist.py=./resources/navidrome_queue_to_playlist.py
      - navidrome_wait.py=./resources/navidrome_wait.py
generatorOptions:
  disableNameSuffixHash: true
