apiVersion: v1
kind: Secret
metadata:
    name: navidrome
    namespace: media
type: Opaque
stringData:
    ND_LASTFM_APIKEY: ENC[AES256_GCM,data:r1cfzxuSjdZ0PAYWs++OtX/IsdUB8abFzagknKTAOhQ=,iv:jDxqg/2Z7kK9olzPjRigDTxfhC6ZrngEo5kRQfCPHmE=,tag:IvIbzZdheHBwynEWEmhE/Q==,type:str]
    ND_LASTFM_SECRET: ENC[AES256_GCM,data:mCVfG/k7RUUEWE34K6INxPN/0dLqU5hxvOsivRqPlVY=,iv:HBR7OiKg8pFaeKAtBbgBFVxPiothjaexwXSFzpydnus=,tag:QXwlT4QE9VRIzLLFgn4hcg==,type:str]
    USERNAME: ENC[AES256_GCM,data:a26ZJVY=,iv:OpxRVDzMXmLwfuQizJpT8S+T+hsjL4eK71gI3jpuaVo=,tag:YxdG6UgduGFqjyJrNxSVsw==,type:str]
    PASSWORD: ENC[AES256_GCM,data:ptrAZkePIpY=,iv:e+X4+Ob7vCU5bR7QKBQjyv4xAQKl43kyopqxthuDeos=,tag:WiiAaOKs4qHpndJPa/umHQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcmo2RTA3RzdCRVhXb3pu
            QVp2S2k4TTJxaEU2Ukowa2VNTTlNMC8rS1JNCjBTNXZSSDVrdVVYa3plMWNWZ0Vt
            cnhjU1FiMEVmNUlqWFdIQ0E2cDNvQ2MKLS0tIGNXWkh4emNUakhXYXZrWkNsNGQw
            QVVacEFTcVhaMktyZG83R3F6Nlhmc28KQxcR8be2ul2zWfQXaAack1muVwkrqg/+
            V/uy79gmdpU890kfXj4BGEqLm1NrTftuJcZDzk8qoF8TMHjYny5Aog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ckmnwzymn6wkqxhyre5kve3leqj5697c59wv3p67jyc5ukzzxpxqxws9wp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T15:37:51Z"
    mac: ENC[AES256_GCM,data:tSauxazzpKEJmQkJ4CED48dyLGMQgoJD1o14VjA9xaW6/F+fS3i5DXMCSsLjPBYx3QcxDdTDrUpsP4zXaqSB7rX7lOMh5whL9DAd3gLv9WksI9xbp3NdUWHay9sIMBfL7DnKFVO+F6E0tnPt+ae+LDAG/gbJyUR8kXs/aVBQ1XU=,iv:glLZSsKGp2VU4P26agJzHJu4k5O+BHFoTgR5bfrKi/0=,tag:WEIDV1G6lcEBgW+dOgaTmA==,type:str]
    version: 3.13.3
