apiVersion: v1
kind: Secret
metadata:
    name: gatus-external
    namespace: monitoring
    labels:
        gatus.io/enabled: "true"
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:iR71d/YEtbFbTZhWMCLMMW77TbQLa35EbvIo3dr6dDVhl2Hb0Ap9C5fTFf3GokmgZaEGShBcV+ZTc3xAamAGs5mMMwsdIqpvZSIGgPIjfN4GdNy9fkZcdIR21QWS7Qx7zfUTFb1HUb1OMzBYHAGCFCaci6r+DJNREHQZdylmXkV066n4CwAWEnuCsetOlfrd9miqoH2AF7APRSPyjcO3CWLFbQt37YJknWAJ3x8A,iv:OJl+/YY70ID6c4OEtfV+qq3n1Ew+5Wl2daFbMGo9tJ8=,tag:HWsN2YqY7mDUJJPxE3osxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeGdMT3JKUWVDNHlQNE5D
            a29iUlRWbWJLT2ZGK2VTRGRoUFZSWXdMM1dnCmZNVlJUWE56T2ZyZ2ttUHJEY0dL
            WHRSdFhDMGlNa0REK1Z6dlRnVytOaWsKLS0tIEc4VG01UU1TcG9GK09LejBpUDZx
            RzB5VE1ZZGdQV0ZyRVZlV3BMZUVvNGMKFsbFzc87Htp5bDt8VQ3Ib5vxetOy+nEi
            9S9sLcqsJUKl9mMxNDz8Dz9KOPRP6HMVdC4O8vUG1jsjK4bw6EslYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ckmnwzymn6wkqxhyre5kve3leqj5697c59wv3p67jyc5ukzzxpxqxws9wp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T20:50:10Z"
    mac: ENC[AES256_GCM,data:L08ve50OJUCp3dvbIS8f3GxmXTmPqM0IaZqHjL6sjANpWm1wlKovpsgmhFl9LNwCwoQyew4F2cAmBpTIB88SDhutFSxIWHPjSLrWO+mK9imSNdcAuRrts+Q9HY6yj9tb9VexhWcvtH05OTNqmLwjySBnO3dhYPTkRscW1gNsuyg=,iv:D1XNYVqBH0n29THW21mc1V0Muk+BqhVNuNWtoNqOM7E=,tag:c0wBTtYz9ivvwFAK6DkxeQ==,type:str]
    version: 3.13.3
