apiVersion: v1
kind: Secret
metadata:
    name: qui
    namespace: media
type: Opaque
stringData:
    QUI__SESSION_SECRET: ENC[AES256_GCM,data:pZCVeQdNEQgDqMUNJhrP1WywBBWY3y4ORXqotjrbKpMSOBC2/zmJRw==,iv:iP3BZJc9wwNr2j1KiHAfJpJHp6aguzHZ7qgNWpcasBU=,tag:3pCwuMzSO1lU7imqGOkwkw==,type:str]
sops:
    age:
        - recipient: age1ckmnwzymn6wkqxhyre5kve3leqj5697c59wv3p67jyc5ukzzxpxqxws9wp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcmo2RTA3RzdCRVhXb3pu
            QVp2S2k4TTJxaEU2Ukowa2VNTTlNMC8rS1JNCjBTNXZSSDVrdVVYa3plMWNWZ0Vt
            cnhjU1FiMEVmNUlqWFdIQ0E2cDNvQ2MKLS0tIGNXWkh4emNUakhXYXZrWkNsNGQw
            QVVacEFTcVhaMktyZG83R3F6Nlhmc28KQxcR8be2ul2zWfQXaAack1muVwkrqg/+
            V/uy79gmdpU890kfXj4BGEqLm1NrTftuJcZDzk8qoF8TMHjYny5Aog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T23:55:42Z"
    mac: ENC[AES256_GCM,data:2kzBLhb7xsGiWqcYc8XEj93gQG8caeVudWQTpbISJig6ouou3OCD8ZM/6YuAEDi3TTWKNPqlCG6PBG0xgBqthtei62cd0gF2rZppvBMw2LSkbPBhVZreey7pAkT7XNZ6+AbO3g4xqhQvijk0WoEOOs4av0HrDljw1Eo1xSL4zVc=,iv:LmisT/d66WAs6e5UbIFDIzDSyT1jvBP1w7tcKNZzM78=,tag:FizRY1vwhmAgL5M/ka9yNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
